### ISSUE TITLE
Flathub release

### ISSUE THREAD

**Issue by Victor239** [btpf/Alexandria#1]
Great looking reader! Would love to install this as a Flatpak for automatic updates (and it helps for visibility).

**Comment by btpf** [comment]
I would like a Flatpak as well, I'll make this a priority.

**Comment by TCB13** [comment]
+1 for this! Thank you.

**Comment by btpf** [comment]
https://flathub.org/apps/io.github.btpf.alexandria

**Comment by TCB13** [comment]
Thank you!!!

**Comment by bigfatbird** [comment]
Hi, is flathub.org not supported anymore?
