### ISSUE TITLE
Will you consider supporting Chinese books?

### ISSUE THREAD

**Issue by cqjerry** [btpf/Alexandria#13]
Win 11, unable to open Chinese books in any format。
![Snipaste_2023-09-04_12-11-28](https://github.com/btpf/Alexandria/assets/7488975/99bd4f09-a58c-4678-bc2e-32c840dbb995)
![Snipaste_2023-09-04_12-11-14](https://github.com/btpf/Alexandria/assets/7488975/be468a5f-ec30-434a-a301-de3ffa5ec07b)

**Comment by btpf** [comment]
Hi, I am sorry you are facing problems. I cannot replicate the issue, so I will need logs from you.
Please follow these instructions, that way I can get more information.

1. Open the application
2. press CTRL + SHIFT + i
3. import the broken book
4. Right click console and "save as"
![image](https://github.com/btpf/Alexandria/assets/61168382/47726c23-8c55-4a88-8958-6182706a301f)

Please upload the log here. Thanks

**Comment by cqjerry** [comment]
When I import the book, the software quits automatically.
[tauri.localhost-1693808037079.log](https://github.com/btpf/Alexandria/files/12509853/tauri.localhost-1693808037079.log)

**Comment by sr79368142** [comment]
这些书籍是从当当网下载的吗？如果是从当当网下载的，可能是内容编辑上不符合epub规范，也可能是drm没有清理。我有一大批这个封面的电子书，都是从当当网下载的。不过好像用sumatrapdf就可以正常打开的。

**Comment by cqjerry** [comment]
不是当当网下载的，时Zlib上下载的，格式有azws mobi 等，暂时没试过epub格式。每次导入书的时候，程序都自动退出了。再次打开就是上面这个没有书封面的状态，也无法打开书籍阅读。

**Comment by btpf** [comment]
So there was a bug I discovered yesterday that would lead to similar behavior and could be related.
1. take the book file
2. delete the entire filename (To erase invisible characters)
3. rename it with latin/english characters only with the .epub extension. 

Then try to import it and tell me if it still crashes.

**Comment by cqjerry** [comment]
Nice ,  It 's working!  Thank you!

**Comment by btpf** [comment]
Great! 
I think I know where the issue is located now. Ill try to develop & deploy a proper solution tomorrow if I have time. 
Thanks for reporting this issue. I will update here once ready for retesting.

**Comment by sr79368142** [comment]
这个和语言没关系，我刚才解压了一本，看了一下内容，是加密的，在META-INF文件夹里有个encryption.xml文件。
如果不想解压的话，可以用sigil或者calibre自带的编辑器测试。
查了一下，epub标准里，epub支持XML加密，所以制作者通过添加一个encryption.xml文件就可以伪装成 DRM， 制作者只是在encryption.xml里随便写了个[加密算法]的信息，然而并不是真的用这个加密算法来加密了文件，目的只是为了阻止calibre或sigil这些能编辑epub的软件打开，但是用特定的阅读软件也是能打开的，所以不是真的DRM。
https://www.zhihu.com/question/399474287

**Comment by btpf** [comment]
Hi @cqjerry , Please test the latest version and tell me if issue is still present. Thanks!
https://github.com/btpf/Alexandria/releases/tag/0.9.3

**Comment by cqjerry** [comment]
Thank you for your work, now is perfact!

**Comment by cqjerry** [comment]
> Hi @cqjerry , Please test the latest version and tell me if issue is still present or if it is now working. Thanks! https://github.com/btpf/Alexandria/releases/tag/0.9.3

Sorry, new bug.  when import file "TheEconomist.2023.09.02.epub", software quit again. I guess it still  file name fault problem.

**Comment by btpf** [comment]
This might be because of the multiple dots. Ill give this a try now.

**Comment by btpf** [comment]
> > Hi @cqjerry , Please test the latest version and tell me if issue is still present or if it is now working. Thanks! https://github.com/btpf/Alexandria/releases/tag/0.9.3
> 
> Sorry, new bug. when import file "TheEconomist.2023.09.02.epub", software quit again. I guess it still file name fault problem.

Can you tell me the size of that file? This problem has nothing to do with the filename this time.

**Comment by cqjerry** [comment]
> > > Hi @cqjerry , Please test the latest version and tell me if issue is still present or if it is now working. Thanks! https://github.com/btpf/Alexandria/releases/tag/0.9.3
> > 
> > 
> > Sorry, new bug. when import file "TheEconomist.2023.09.02.epub", software quit again. I guess it still file name fault problem.
> 
> Can you tell me the size of that file? I don't think this problem has anything to do with the filename this time.
> 
> I highly suspect the epub you have is corrupt. Can you try it in calibre and tell me if it is working?

https://github.com/hehonghui/awesome-english-ebooks/tree/master/01_economist/te_2023.09.02      file location

**Comment by btpf** [comment]
This file downloaded multiple times incomplete. When it did download, and was 16.4MB on the filesystem, it opened fine. 
I will prevent crashing when importing corrupt epubs with the next version.
It also seems like the image will stretch incorrectly in the library view. I will investigate this bug.
Since this specific issue is solved, I will close now.
Thanks!
