### ISSUE TITLE
Customize text alignment

### ISSUE THREAD

**Issue by HoratioVex** [btpf/Alexandria#16]
Feature suggestion:
An option should be added to override the book default of the "text-align" property, minimally to choose between "left" and "justify", possibly adding "right" and "center".

I'm not sure where it would best fit. "Spacing" would be logical, but "Display" might look better.

**Comment by btpf** [comment]
Thanks for the suggestion. I decided to squeeze text-alignment into spacing, I don't think it came out bad at all. 
You can get the latest update here: https://github.com/btpf/Alexandria/releases/tag/v0.11.0
Enjoy!
