### ISSUE TITLE
Covers and books not loading after 0.11.0 update.

### ISSUE THREAD

**Issue by Nutjob** [btpf/Alexandria#20]
After updating to 0.11.0 the covers are not loaded in Library, and opening a book causes it to be empty, with the lower bar stuck in "loading...", the previous version worked perfectly.

This has been tested with Flatpak on Ubuntu 18.04.05 and SteamOS 3.4.11, both system have the same bug.

**Comment by btpf** [comment]
Hi,
Thanks for the report. 
- This bug affects all Linux builds.
- I am deploying a fix now.
- The Flatpak should be updated within the next 12 hours.

Sorry for the interruption.
