### ISSUE TITLE
"Add Installed Font" bugs

### ISSUE THREAD

**Issue by HoratioVex** [btpf/Alexandria#21]
Using: Alexandria v11.0 x64 portable (Win10)

I realize the function is flagged as temporary workaround, just reporting for completeness' sake.

1. It accepts names that don't exist, leading to dummy entries.
2. No entry from this function, dummy or real, can be deleted from the UI. It just reappears whenever you open the menu and must be deleted from the JSON manually.

**Comment by btpf** [comment]
1. I am aware this isn't a great solution, it was a fast lazy one (for my own use). I may look into adding [font-kit](https://github.com/servo/font-kit) to list system fonts alongside the downloadable google fonts. This is a more complete solution.

2. This is a bug. I left a guard clause in I forgot to remove when adding the feature.  

I will probably fix this bug alongside the font-kit integration in the next release. Thanks for reporting.

**Comment by btpf** [comment]
Both of the issues are fixed in the latest release:

https://github.com/btpf/Alexandria/releases/tag/v0.11.2
