### ISSUE TITLE
Linux -- Incorrect Version Reported

### ISSUE THREAD

**Issue by ddewett** [btpf/Alexandria#25]
Platform: Linux
Issue: Installing with Flatpak installs the 0.11.1 version and not the 0.11.2 version.
Steps:
```
flatpak install io.github.btpf.alexandria
flatpak info io.github.btpf.alexandria
```
>...
ID: io.github.btpf.alexandria
Ref: app/io.github.btpf.alexandria/x86_64/stable
Arch: x86_64
Branch: stable
Version: 0.11.2
...

```
flatpak run io.github.btpf.alexandria
```
[in GUI: settings > about]
>...
Version 0.11.1
...

Comments: The bug that 0.11.2 was intended to fix (https://github.com/btpf/Alexandria/issues/20) is still observed. `flatpak info` reports the correct version, but the UI does not. Since the bug is still observed, I assume that the version reported by `flatpak info` is incorrect.

**Comment by btpf** [comment]
Hi, the Flatpak was not updated correctly. I will fix this immediately. 
Thanks for reporting.

https://github.com/flathub/io.github.btpf.alexandria/pull/7
