### ISSUE TITLE
Highlight Rectangles Overlap Causing Inconsistent Highlight Visual

### ISSUE THREAD

**Issue by ddewett** [btpf/Alexandria#27]
# Issue: The rectangles used to display the highlighted text overlap, which causes inconsistent highlight color.
### Settings:
* Font - Default
* Font Size - 100%
* Font Weight - 400
* Word Spacing - 0px
* Line Height - 100%
* Reader Margins - 25%
* Paragraph Spacing - default
* Theme - Any

### Steps:
1) Display text that covers multiple lines.
2) Highlight text with mouse and apply color using popup.
3) The spaces between some lines will display darker. This is due to the opacity (0.3) being applied to the SVG rectangles that are overlapping, which creates a situation where layered opacity causes an effective decrease in the opacity being applied. Changing the line spacing will eventually cause the overlap to go to zero and then negative (i.e., an empty space will exist between the lines). This effect is due to the static rectangle height (it is not keyed to line height). Setting a negative line height will remove the overlap in test cases.
![Line Height at 100%](https://github.com/btpf/Alexandria/assets/31186788/69727ad0-8a43-45d6-9c40-3a9de0e25d3e)

![Line Height at -5%](https://github.com/btpf/Alexandria/assets/31186788/1c7cc42b-f818-4f1b-aa03-3c6bd7de140b)

**Comment by btpf** [comment]
I made it so the highlights will recalculate their height based on your line-height and font-size. In my testing, this greatly helps in reducing this problem but doesn't eliminate it. 

This will be pushed in the next release.
