### ISSUE TITLE
Hyperlink Text Color is Not Honored

### ISSUE THREAD

**Issue by ddewett** [btpf/Alexandria#29]
# Issue: The rectangles used to display the highlighted text overlap, which causes inconsistent highlight color.
### Settings:
* Font - Default
* Font Size - 100%
* Font Weight - 400
* Word Spacing - 0px
* Line Height - 100%
* Reader Margins - 25%
* Paragraph Spacing - default
* Theme - Any

### Steps:
1) Change theme colors
![Screenshot from 2024-01-10 21-22-12](https://github.com/btpf/Alexandria/assets/31186788/166f256a-473d-475f-b38a-b7e83fe5173a)

2) View a file with a valid hyperlink. Inspecting the hyperlink shows the hyperlink tag.
![Screenshot from 2024-01-10 21-21-58](https://github.com/btpf/Alexandria/assets/31186788/6dee3c6c-df82-4e8a-857c-81a8e86e36bf)

3) Note the color of the hyperlink is black. None of the theme colors are black. This is true for the table of contents as well:
![Screenshot from 2024-01-10 21-26-04](https://github.com/btpf/Alexandria/assets/31186788/5035b0fe-6879-440a-8edb-6ac4949d8eee)

**Comment by btpf** [comment]
Fixed With https://github.com/btpf/Alexandria/issues/36#issuecomment-1891208437
