### ISSUE TITLE
Embedded Span Tags Break Copy Highlighted Text

### ISSUE THREAD

**Issue by ddewett** [btpf/Alexandria#30]
# Issue: Embedded page breaks in the EPUB file are translated into SPAN tags in the HTML. These tags cause select and copy text features to break.
### Settings:
* Font - Default
* Font Size - 100%
* Font Weight - 400
* Word Spacing - 0px
* Line Height - 100%
* Reader Margins - 25%
* Paragraph Spacing - default
* Theme - Any

### Steps:
1) Display text that covers an embedded SPAN tag. These are assigned as "pagebreaks," but are invisible in flowable text.
![Screenshot from 2024-01-10 21-38-33](https://github.com/btpf/Alexandria/assets/31186788/4caf2b42-d25e-4402-9942-8c07417e17e6)

2) Highlight text with mouse and copy using the popup.
3) User received "Text Copied" toast message.
4) Pasting into another context (e.g., a different application) only pastes the text following the SPAN tag. This implies that the SPAN tag is segmenting the text copied to the clipboard into multiple streams, and the last one is retained.

**Comment by btpf** [comment]
An explanation of these tags: https://www.mobileread.com/forums/showthread.php?t=331107

This will be fixed in the next release.
