### ISSUE TITLE
Feature Request: Ability to Change Color of Fly-out Features

### ISSUE THREAD

**Issue by ddewett** [btpf/Alexandria#32]
# Description: 
When using custom themes, it is possible to make the background such that the active tab highlights (blue) and the contents drop-down arrows do not have enough contrast to easily see.

## Request: 
* Make these agree with the "Secondary Text" and "Primary Text" color or enable changing them directly in the Theme Settings page.
* Make the example in Theme Settings show these elements.

![Screenshot from 2024-01-10 22-24-46](https://github.com/btpf/Alexandria/assets/31186788/b966673e-5e6d-4dd6-b3b9-911e7e05d413)

#### Secondary Text
"Secondary Background" is used for the fly-out background. This is clear to the user by looking at the miniature example given on this screen. However, the tab headings and drop-down arrows are not on this example. Therefore, the user has no idea what these will look like until they navigate to this in the application. 

**By setting the active tab to the same as "Secondary Text" the UI is color consistent.**

#### Drop-down Arrows
The drop-down arrows have a different color in both provided themes. The user cannot directly control which is used in a custom theme. 

The visual improvement of this in the provided themes is minor, and keeping this requires an additional setting in the Theme Settings to accommodate custom themes (either explicitly select this color or toggle between the preexisting two that are available). 

**Setting this color to the same as "Primary Text" solves all the usability issues at the expense of minor visual changes.** The color difference between the arrows in both the provided Light and Dark themes are minor enough that maintaining the same color as the text won't impact usability.

**Comment by btpf** [comment]
I would like to thank you for taking the time to write such detailed reports. Ill try to work through them and aim to push out the next release around the 20th.

**Comment by ddewett** [comment]
👍🏻
