### ISSUE TITLE
can not open the book

### ISSUE THREAD

**Issue by wyf195075595** [btpf/Alexandria#47]
when i open the book, dist file has error
![image](https://github.com/btpf/Alexandria/assets/60338824/bfa9d793-ee76-4819-b7e6-58651d140fd2)

[Alexandria_0.12.0_x64-setup.exe]

**Comment by btpf** [comment]
Hi, I am sorry you are facing problems . I will need logs from you.
Please follow these instructions, that way I can get more information.

Open the application
press CTRL + SHIFT + i
Open the broken book
Right click console and "save as"
![image](https://github.com/btpf/Alexandria/assets/61168382/e4916571-c6d7-4291-ba7b-fe0e5cc1e76b)

If there are multiple errors in console, sharing a screenshot of it may better assist me

Also the below questions will help me:
Does the image preview for the book show?
What file format is the book in?
What is the title of the book?
 
 Thanks!

**Comment by F-TD5X** [comment]
[console.log](https://github.com/user-attachments/files/16643347/console.log)
I have same issue, and this is my console log.
