### ISSUE TITLE
How to make My Preferences the default preference option for opening eBooks

### ISSUE THREAD

**Issue by delong130** [btpf/Alexandria#48]
Every time I open a new book, I use the system's default layout, font, size, and spacing. I have to go back and set these every time. Is it possible to implement various personalized settings of my personal preferences as defaults, so that when I open a new book it is the way I like it?

Thank you very much!

**Comment by btpf** [comment]
I believe the bug you described has been fixed. I have a build that you can use in the meantime if you want to test the fix before next release.

https://github.com/btpf/Alexandria/actions/runs/9010574904
https://github.com/btpf/Alexandria/actions/runs/9010574904/artifacts/1486199854

**Comment by DejayRezme** [comment]
I think this is a duplicate for #41. I tried the build from 3 weeks ago and it doesn't look fixed.

**Comment by btpf** [comment]
Ok I see, I fixed a bug in that release which didn't save the selected global theme when inside of a book. 

Ill merge this issue into #41 and look into this for the next release.
