### ISSUE TITLE
Hi Y Combinator

### ISSUE THREAD

**Issue by btpf** [btpf/Alexandria#6]
Hi Everyone.

I opened github and saw that the project I was hoping to debut incrementally had exploded.
Google searching showed that this attention comes from my app being reposted on YCombinator. 
So...Welcome :)

This attention is a little overwhelming and there is much to do so please bear with me.

Current Issues (In Order of priority)
- ~~AppImage will display error the first time a book is opened~~
- ~~AppImage do not display book covers (Fix Pending Deployment)~~
- ~~Currently, Appimage will crash on launch with systems using an older version of glibc. This is caused because I am building on Arch. A CI/CD system will need to be set up for this.~~
- Flatpak will be used for support of different distros.

**Comment by sigio** [comment]
I've installed the .deb version.... but so far it hasn't opened anything i've added to it yet... either completely crashing or giving 'No Section Found'. But good luck with this project. I might check it out when it hits 1.0 and cbz formats are supported.

**Comment by benjstarratt** [comment]
I saw your comment that you don't have access to a Mac.  I have an M2, iPad Pro, etc.  If I could be of assistance, let me know.  I am not a developer, but I do use VSCode and git for infrastructure.  I'd need some advice on setting up the build environment since that isn't something I do.  I'm guessing react, node, nvm and some other stuff.  Reply back if you are interested--I am watching the project and will see it.

**Comment by btpf** [comment]
> I saw your comment that you don't have access to a Mac. I have an M2, iPad Pro, etc. If I could be of assistance, let me know. I am not a developer, but I do use VSCode and git for infrastructure. I'd need some advice on setting up the build environment since that isn't something I do. I'm guessing react, node, nvm and some other stuff. Reply back if you are interested--I am watching the project and will see it.

This is incredibly generous. Although I think a MacOS build could be accomplished in a single day, getting that done would be very challenging for me since I am completely unfamiliar with the MacOs platform & developer ecosystem. 
I will soon open up a separate issue asking for technical help since I know there are people who can breeze through this process.
