### ISSUE TITLE
Sync with CRDTs

### ISSUE THREAD

**Issue by ruihildt** [btpf/Alexandria#8]
Hi,

Didn't find any contact info, so opening an issue.

Looking at your sync issue in the FAQ, it seems to me that Alexandria is one software that would benefit from the local first approach (https://localfirstweb.dev/).

If you haven't looked at it yet, I would have a look at CRDTs, like automerge or yjs.

Pretty sure you're aware of those, so I'm curious about your take on it.

**Comment by btpf** [comment]
This looks like an amazing resource to learn from. Thanks!
